services:
  qbittorrent:
    image: ${IMAGE_QBITTORRENT}
    container_name: ${QBITTORRENT_CONTAINER_NAME}
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${QBITTORRENT_TIMEZONE}
      TORRENTING_PORT: ${QBITTORRENT_PORT_TORRENT}
    network_mode: "service:gluetun"
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${QBITTORRENT_VOLUME}/themes:/themes
      - ${HOMESERVER_VOLUME_SFTP_TORRENT}:/data/downloads
    restart: unless-stopped
