services:
  deluge:
    image: ${IMAGE_DELUGE}
    container_name: ${DELUGE_CONTAINER_NAME}
    environment:
      TZ: ${DELUGE_TIMEZONE}
      DELUGE_LOGLEVEL: ${DELUGE_LOG_LEVEL} #optional
    network_mode: "service:gluetun"
    volumes:
      - ${DELUGE_VOLUME}/config:/config
      - ${HOMESERVER_VOLUME_SFTP_DOWNLOAD}:/downloads
    restart: unless-stopped
