services:
  jellyfin:
    image: ${IMAGE_JELLYFIN}
    container_name: ${JELLYFIN_CONTAINER_NAME}
    labels:
      traefik.http.routers.jellyfin.entrypoints: http
      traefik.http.routers.jellyfin.rule: Host(${REVERSE_PROXY_HOST_JELLYFIN})
      traefik.http.routers.jellyfin.tls: false
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.routers.jellyfin.middlewares: jellyfin-redirect-https
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.middlewares.jellyfin-redirect-https.redirectscheme.scheme: https
      # https
      traefik.http.routers.jellyfin-secure.entrypoints: https
      traefik.http.routers.jellyfin-secure.rule: Host(`${HOST_PROXY_JELLYFIN}`)
      traefik.http.routers.jellyfin-secure.tls: true
      traefik.http.routers.jellyfin-secure.service: jellyfin-secure
      traefik.http.services.jellyfin-secure.loadbalancer.server.port: 8096
    networks:
      - ${HOMESERVER_NETWORK_REVERSE_PROXY}
    ports:
      - ${JELLYFIN_PORT_WEB_UI}:8096
    volumes:
      - ${JELLYFIN_VOLUME}/config:/config
      - ${JELLYFIN_VOLUME}/cache:/cache
      #- ${JELLYFIN_VOLUME_OWNCLOUD}:/media:ro # owncloud
      - ${JELLYFIN_VOLUME_SFTPGO}:/media:ro # sftp with sftpgo
    restart: unless-stopped
