api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  pihole-tcp-dns:
    address: ":53/tcp"
  pihole-udp-dns:
    address: ":53/udp"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    network: "<your-traefik-global-network>"
  file:
    filename: "/etc/traefik/traefik.yml"
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "<your-email@domain.com>"
      storage: acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  cloudflare-staging:
    acme:
      email: "<your-email@domain.com>"
      storage: acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
