services:
  pihole:
    container_name: ${PIHOLE_CONTAINER_NAME}
    image: ${IMAGE_PIHOLE}
    environment:
      TZ: ${PIHOLE_TIMEZONE}
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PIHOLE_DNS_: ${PIHOLE_DNS_LIST}
    labels:
      # pihole router
      traefik.http.routers.pihole.entrypoints: http
      traefik.http.routers.pihole.rule: ${REVERSE_PROXY_HOST_PIHOLE}
      traefik.http.routers.pihole.tls: false
      # pihole service
      traefik.http.routers.pihole.service: pihole
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.http.routers.pihole.middlewares: pihole-redirect-admin, pihole-redirect-https
      # pihole middleware
      traefik.http.middlewares.pihole-redirect-admin.redirectregex.regex: "^http:\\/\\/([^\\/]+)\\/?$$"
      traefik.http.middlewares.pihole-redirect-admin.redirectregex.replacement: "http://$$1/admin"
      traefik.http.middlewares.pihole-redirect-https.redirectscheme.scheme: ${PIHOLE_REDIRECT}

      # pihole-secure router
      traefik.http.routers.pihole-secure.entrypoints: https
      traefik.http.routers.pihole-secure.rule: Host(`${HOST_PROXY_PIHOLE}`)
      traefik.http.routers.pihole-secure.tls: true
      # pihole-secure service
      traefik.http.routers.pihole-secure.service: pihole-secure
      traefik.http.services.pihole-secure.loadbalancer.server.port: 80
      # pihole-secure middleware
      traefik.http.routers.pihole-secure.middlewares: pihole-secure-redirect-admin
      traefik.http.middlewares.pihole-secure-redirect-admin.redirectregex.regex: "^https:\\/\\/([^\\/]+)\\/?$$"
      traefik.http.middlewares.pihole-secure-redirect-admin.redirectregex.replacement: "https://$$1/admin"
    networks:
      - ${HOMESERVER_NETWORK_REVERSE_PROXY}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_PORT_WEB_UI}:80/tcp
    volumes:
      - ${PIHOLE_VOLUME}/etc/pihole:/etc/pihole
      - ${PIHOLE_VOLUME}/etc/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
